# Generated by Django 4.2.1 on 2023-05-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created_jobs',
            field=models.IntegerField(verbose_name='Number of Created Jobs'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='econ_sector',
            field=models.IntegerField(choices=[(0, 'Agriculture, Forestry, Fishing and Hunting'), (1, 'Mining, Quarrying, and Oil and Gas Extraction'), (2, 'Utilities'), (3, 'Construction'), (4, 'Manufacturing'), (5, 'Wholesale Trade'), (6, 'Retail Trade'), (7, 'Transportation and Warehousing'), (8, 'Information'), (9, 'Finance and Insurance'), (10, 'Real Estate and Rental and Leasing'), (11, 'Professional, Scientific, and Technical Services'), (12, 'Management of Companies and Enterprises'), (13, 'Administrative and Support and Waste Management and Remediation Services'), (14, 'Educational Services'), (15, 'Health Care and Social Assistance'), (16, 'Arts, Entertainment, and Recreation'), (17, 'Accommodation and Food Services'), (18, 'Other Services (Except Public Administration)'), (19, 'Public Administration')], verbose_name='Economy Sector'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='internal_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='no_emp',
            field=models.IntegerField(verbose_name='Number of Current Employees'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='retained_jobs',
            field=models.IntegerField(verbose_name='Number of Retained Jobs'),
        ),
    ]
