# Generated by Django 4.2.1 on 2023-05-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_created_jobs_alter_loan_econ_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
