# Generated by Django 4.2.1 on 2023-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_email_alter_loan_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
