# Generated by Django 4.2.1 on 2023-05-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model', models.BinaryField()),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('train_samples', models.IntegerField()),
                ('test_samples', models.IntegerField()),
                ('train_time', models.TimeField()),
                ('max_depth', models.IntegerField()),
                ('min_child_weight', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('subsample', models.FloatField()),
                ('colsample_bytree', models.FloatField()),
                ('colsample_bylevel', models.FloatField()),
                ('colsample_bynode', models.FloatField()),
                ('alpha', models.FloatField()),
                ('reg_lambda', models.FloatField()),
                ('gamma', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('active_update_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
